computer/urls.py
from django.urls import path
from . import views

urlpatterns = [ # 서버IP/computer
#    path('<int:pk>/', views.single_computer_page),
#    path('', views.index),

    path('search/<str:q>/', views.ItemSearch.as_view()),
    path('update_item/<int:pk>/',views.ItemUpdate.as_view()),
    path('<int:pk>/update_comment/',views.CommentUpdate.as_view()),
    path('create_item/',views.ItemCreate.as_view()),
    path('category/<str:slug>', views.category_page),
    path('maker/<str:slug>', views.maker_page),
    path('<int:pk>/new_comment/',views.new_comment),
    path('<int:pk>/', views.ItemDetail.as_view()),
    path('', views.ItemList.as_view()),
]

final_prj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('computer/', include('computer.urls')), # 서버IP/computer
    path('admin/', admin.site.urls), # 서버IP/admin
    path('', include('single_pages.urls')), # 서버IP/
    path('accounts/',include('allauth.urls')),
    path('markdownx/', include('markdownx.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) # 서버IP/media/

computer/models.py
from django.db import models
from django.contrib.auth.models import User
import os
from markdownx.models import MarkdownxField
from markdownx.utils import markdown
# Create your models here.

class Maker(models.Model):
    maker_name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
    maker_address = models.CharField(max_length=50)
    maker_contact = models.CharField(max_length=50)
    maker_certificate = models.CharField(max_length=50)
    maker_certificate_name = models.CharField(max_length=50)

    def __str__(self):
        return self.maker_name

    def get_absolute_url(self):
        return f'/blog/maker/{self.slug}'

class Category(models.Model):
    category_name = models.CharField(max_length=50,unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.category_name

    def get_absolute_url(self):
        return f'/blog/category/{self.slug}'

class Item(models.Model):
    item_name = models.CharField(max_length=50)
    explanation = MarkdownxField()
    item_price = models.CharField(max_length=50)

    maker = models.ForeignKey(Maker, null=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)

    head_image = models.ImageField(upload_to='computer/images/%Y/%m/%d', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    item_state = models.CharField(max_length=50)
    item_receipt = models.CharField(max_length=50)

    author = models.ForeignKey(User,null=True,on_delete=models.SET_NULL)

    def __str__(self):
        return f'[{self.pk}] {self.item_name} :: {self.author}'

    def get_absolute_url(self):
        return f'/computer/{self.pk}/'

    def get_explanation_markdown(self):
        return markdown(self.explanation)

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else :
            return 'https://doitdjango.com/avatar/id/367/f8b6bb3fdf643ed8/svg/{self.author.email}/'

class Comment(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        return f'{self.item.get_absolute_url()}#comment-{self.pk}'

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()

        else :
            return 'https://doitdjango.com/avatar/id/367/f8b6bb3fdf643ed8/svg/{self.author.email}/'

computer/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

computer/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from .models import Item, Maker,Category, Comment
from django.core.exceptions import PermissionDenied
from .forms import CommentForm
from django.shortcuts import get_object_or_404
from django.db.models import Q
# Create your views here.

def new_comment(request, pk):
    if request.user.is_authenticated:
        item = get_object_or_404(Item, pk=pk)
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.item = item
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else:
            return redirect(item.get_absolute_url())
    else:
        raise PermissionDenied

class ItemCreate(LoginRequiredMixin,UserPassesTestMixin,CreateView):
    model = Item
    fields = ['item_name','explanation','item_price','maker','category','head_image','item_state','item_receipt']

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            form.instance.author = current_user
            return super(ItemCreate,self).form_valid(form)
        else :
            return redirect('/computer/')

class ItemUpdate(LoginRequiredMixin,UpdateView):
    model = Item
    fields = ['item_name','explanation','item_price','maker','category','head_image','item_state','item_receipt']

    template_name = 'computer/item_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(ItemUpdate,self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

class CommentUpdate(LoginRequiredMixin,UpdateView):
    model = Comment
    fields = ['content']

    template_name = 'computer/comment_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate,self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


class ItemList(ListView) :
    model = Item
    ordering = '-pk'
    paginate_by = 8

    def get_context_data(self, *, object_list=None, **kwargs):
        c_context = super(ItemList,self).get_context_data()
        c_context['categories'] = Category.objects.all()
        c_context['no_category'] = Item.objects.filter(category=None).count()
        c_context['makers'] = Maker.objects.all()
        c_context['no_maker'] = Item.objects.filter(maker=None).count()
        return c_context

#    template_name = 'computer/item_list.html'
# item_list.html

class ItemDetail(DetailView) :
    model = Item

    def get_context_data(self, *, object_list=None, **kwargs):
        c_context = super(ItemDetail,self).get_context_data()
        c_context['categories'] = Category.objects.all()
        c_context['no_category'] = Item.objects.filter(category=None).count()
        c_context['makers'] = Maker.objects.all()
        c_context['no_maker'] = Item.objects.filter(maker=None).count()
        c_context['comment_form'] = CommentForm
        return c_context

class ItemSearch(ItemList) :
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        item_list = Item.objects.filter(
            Q(item_name__contains=q) | Q(explanation__contains=q)
        ).distinct()
        return item_list

    def get_context_data(self, **kwargs):
        context = super(ItemSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search : {q}({self.get_queryset().count()})'
        return context

def category_page(request, slug):
    if slug == 'no_category' :
        category = '미분류'
        item_list = Item.objects.filter(category=None)
    else :
        category = Category.objects.get(slug=slug)
        item_list = Item.objects.filter(category=category)

    return render(request, 'computer/item_list.html',
                  {
                      'item_list' : item_list,
                      'categories' : Category.objects.all(),
                      'no_category' : Item.objects.filter(category=None).count(),
                      'category' : category
                  }
                  )

def maker_page(request, slug):
    if slug == 'no_maker' :
        maker = '미분류'
        item_list = Item.objects.filter(maker=None)
    else :
        maker = Maker.objects.get(slug=slug)
        item_list = Item.objects.filter(maker=maker)

    return render(request,  'computer/item_list.html',
                  {
                      'item_list' : item_list,
                      'makers' : Maker.objects.all(),
                      'no_maker' : Item.objects.filter(maker=None).count(),
                      'maker' : maker
                  }
                  )



# item_detail.html

#def index(request) :
#    items = Item.objects.all().order_by('pk')

#    return render(request, 'computer/item_list.html',
#                  {
#                      'items' : items
#                  }
#                  )

#def single_computer_page(request, pk) :
#    item = Item.objects.get(pk=pk)

#    return render(request, 'computer/item_detail.html',
#                  {
#                      'item' : item
#                  }
#                  )

computer/templates/computer/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <title> {% block head_title %} SCP {% endblock %}</title>
    <link href = "{% static 'computer/bootstrap/bootstrap.min.css' %}" rel = "stylesheet" type = "text/css" media = "screen">
    <link href="{% static 'single_pages/css/landing.css' %}" rel = "stylesheet" type = "text/css" media="screen">
    <link href = "{% static 'computer/css/computer-item.css' %}" rel = "stylesheet" type = "text/css" media = "screen">
    <script src="https://kit.fontawesome.com/0df8adaa6b.js" crossorigin="anonymous"></script>
     <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />

    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type = "text/css" media="screen" />

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'computer/bootstrap/styles.css' %}" rel = "stylesheet" type = "text/css" media = "screen" />
</head>
<body>
    {% include 'computer/navbar.html' %}

        {% block main_area %}
        {% endblock %}

        <script>
            function searchItem(){
                let searchValue = document.getElementById('search-input').value.trim();
                if(searchValue.length > 1){
                    location.href = "/computer/search/" + searchValue +"/";
                }
                else{
                    alert('검색어(' + searchValue +')가 너무 짧습니다. ');
                }
            };
            document.getElementById('search-input').addEventListener('keyup',
                            function(event){
                                if(event.key == 'Enter'){ searchItem();}
                            }
            )
        </script>


        {% include 'computer/footer.html' %}


        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!--Javascript Bootstrap-->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

    </body>
</html>

computer/templates/computer/comment_form.html
{% extends 'computer/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    Edit Comment - SCP
{% endblock %}
{% block main_area %}

<hr>
    <div class="container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="container bg-light row my-3 ">
                <h1 class="bg-light row my-3">Edit Comment</h1>
                {{form | crispy}}
                <br>
                <button type="submit" class="btn btn-primary row my-3">Edit</button>

            </div>
        </form>
    </div>
    {{form.media}}
{% endblock %}

computer/templates/computer/item_detail.html
{% extends 'computer/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    {{ item.item_name }} - SCP
{% endblock %}

{% block main_area %}

        <!-- Product section-->
        <div class="py-5 mb-2" id="item-area">
            <div class="container px-4 px-lg-5 my-5 mb-2">
                <div class="row gx-4 gx-lg-5 align-items-center mb-2">


                    <div class="container-fluid mb-2">
                        <div class = "col-20">
                            <!-- Search widget-->
                            <div class="card mb-2 bg-success " >
                                <div class="card-body">
                                <div class="input-group">
                                    <input class="form-control" type="text" id="search-input" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                    <button class="btn btn-secondary" id="button-search" type="button" onclick="searchItem()">Go!</button>
                                </div>
                            </div>
                        </div>
                        </div>
                    </div>

                    {% if item.head_image.url %}
                        <div class="col-md-4 mb-2"><img class="card-img-top mb-5 mb-md-0" src="{{ item.head_image.url }}" alt="{{item}}의 head이미지" /></div>
                    {% else %}
                        <div class="col-md-4 mb-2"><img class="card-img-top mb-5 mb-md-0" src="https://picsum.photos/seed/{{item.id}}" alt="random image" /></div>
                    {% endif %}

                    <div class="col-md-8 bg-dark">
                        <div class="row-my-3">
                        <h1 class="display-5 fw-bolder"></h1>
                        <h1 class="lead bg-light font-weight-bold">{{ item.item_name }}</h1>
                        <div class="lead bg-light">
                            {{ item.get_explanation_markdown |safe }}
                        </div>
                            <h3 class="lead bg-light font-weight-bold">제조사 : {{ item.maker }}</h3>
                            <h3 class="lead bg-light font-weight-bold">종류 : {{ item.category }}</h3>
                            <h3 class="lead bg-light font-weight-bold">상품 상태 : {{ item.item_state }}</h3>
                            <h3 class="lead bg-light font-weight-bold">영수증 가능 여부 : {{item.item_receipt}}</h3>
                            <h3 class="lead bg-light font-weight-bold">{{ item.item_price }}원</h3>

                        </div>

                        <div class = "row-my-3 text-muted bg-light float-right">
                            {{ item.created_at | date:"20y-m-d" }} by {{item.author | upper}}
                        </div>
                        <br>
                        {% if user.is_authenticated %}
                        <div class="row-my-3 float-left">
                            <a class="btn btn-secondary float-left my-2" type="button">
                                <i class="bi-cart-fill me-1"></i>
                                Add to cart
                            </a>

                        </div>
                        {% endif %}
                        {% if user.is_authenticated and user == item.author %}
                            <a href ="/computer/update_item/{{item.pk}}/"
                               class="btn btn-secondary float-right my-2">
                                <i class="fas fa-pen"></i>
                                Edit Post
                            </a>
                            {% endif %}
                    </div>

                    <div class="container my-2">
                        <!-- Categories widget-->
                        <div class="card mb-2 bg-light" id="categories-card">
                            <div class="card-body">
                                <div class="row">
                                    <ul class = "list-unstyled mb-0">
                                        {% for c in categories %}
                                        <a class ="btn btn-success"  href="http://127.0.0.1:8000/computer/category/{{c.slug}}">{{c}} ({{c.item_set.count}})</a>
                                        {% endfor %}
                                        <a class ="btn btn-success" href="http://127.0.0.1:8000/computer/category/no_category">미분류 ({{no_category}})</a>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    <!-- Maker widget-->
                        <div class="card mb-2" id="maker-card">
                            <div class="card-body">
                                <div class="row">
                                    <ul class = "list-unstyled mb-0">
                                        {% for c in makers %}
                                        <a class ="btn btn-success" href="http://127.0.0.1:8000/computer/maker/{{c.slug}}">{{c}} ({{c.item_set.count}})</a>
                                        {% endfor %}
                                        <a class ="btn btn-success" href="http://127.0.0.1:8000/computer/maker/no_maker">미분류 ({{no_maker}})</a>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    <!-- Comments section-->
                        <div class="mb-5" id="comment-area">
                            <div class="card bg-light">
                            <div class="card-body">
                            <!-- Comment form-->
                                {% if user.is_authenticated %}

                                <form class="mb-1" id="comment-form" method="POST" action="{{item.get_absolute_url}}new_comment/">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        {{comment_form | crispy}}
                                    </div>
                                    <div class="float-right">
                                    <button type="submit" class="btn btn-secondary">Submit</button>
                                    </div>
                                    <br>
                                </form>
                                {% else %}
                                    <a role="button" class="btn btn-secondary" href="#"
                                       data-toggle="modal" data-target="#loginModal"
                                    >Log in and leave a comment</a>
                                {% endif %}


                            <section>
                                <!-- Comment with nested comments-->
                                {% if item.comment_set.exists %}
                                {% for c in item.comment_set.all %}

                                <div class="d-flex mb-4">
                                    <!-- Parent comment-->
                                    <div class="d-flex" id="comment-{{c.pk}}">
                                        <div class="flex-shrink-0">
                                            <img class="rounded-circle" src="{{c.get_avatar_url}}" alt="{{c.author}}" width="60px"/>
                                        </div>

                                    <div class="ms-3">
                                            <div class="fw-bold">{{c.author.username}} &nbsp;&nbsp;<small class="text-muted">{{c.created_at}}</small>

                                                {% if user.is_authenticated and user == c.author %}
                                                <div class="float-right mx-1">
                                                    <a href="/computer/{{c.pk}}/update_comment/">
                                                        <button type="submit" class="btn btn-success btn-sm">Edit</button>
                                                    </a>
                                                </div>
                                                {% endif %}
                                                {% if user.is_authenticated and user == c.author %}
                                                <div class="float-right mx-1">
                                                    <button type="submit" class="btn btn-success btn-sm">Delete</button>
                                                </div>
                                                {% endif %}
                                            </div>
                                            <p>{{c.content | linebreaks }}</p>

                                            {% if user.is_authenticated and user == c.author %}
                                            <div class="float-right mx-1">
                                                <a href="/computer/{{c.pk}}/update_comment/">
                                                    <button type="submit" class="btn btn-success btn-sm">Edit</button>
                                                </a>
                                            </div>
                                            {% endif %}
                                            {% if user.is_authenticated and user == c.author %}
                                            <div class="float-right mx-1">
                                                <button type="submit" class="btn btn-success btn-sm">Delete</button>
                                            </div>
                                            {% endif %}

                                        <!-- Child comment 1-->

                                        <div class="d-flex mt-4">
                                            <div class="flex-shrink-0">
                                                <img class="rounded-circle" src="{{c.get_avatar_url}}" alt="{{c.author}}" width="60px"/>
                                            </div>
                                            <div class="ms-3">
                                                <div class="fw-bold">{{c.author.username}} &nbsp;&nbsp;<small class="text-muted">{{c.created_at}}</small></div>
                                                <p>{{c.content | linebreaks }}</p>

                                            </div>
                                        </div>
                                    </div>
                                    </div>
                                </div>
                                {% endfor %}
                                {% endif %}
                            </section>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>


{% endblock %}

computer/templates/computer/item_list.html
{% extends 'computer/base.html' %}
{% block main_area %}

        <h1>{% if category %} <span class="badge bg-secondary">{{category}}</span> {% endif %} {% if maker %}<span class="badge bg-secondary">{{maker}}</span> {% endif %} </h1>
        <!-- Header-->
    <div class="container">
        <header class="bg-dark py-5 pt-5">
            <div class="container px-4 px-lg-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">SCP</h1>
                    <p class="lead fw-normal text-white-50">Specialization In Computer Parts</p>
                </div>
            </div>
        </header>
    </div>

        <!-- Computer Item Section-->
        <section class="py-0">
            <div class="container px-3 px-lg-5 mt-5">
                <div class = "col-20">
                        {% if user.is_authenticated %}
                            {% if user.is_staff or user.is_superuser %}
                                <a class="btn btn-secondary mb-2 " href="/computer/create_item"><i class="fas fa-pen"></i> New Item</a>
                            {% endif %}
                        {% endif %}
                    <!-- Search widget-->
                            <div class="card mb-2 bg-success " >
                                <div class="card-body">
                                <div class="input-group">
                                    <input class="form-control" type="text" id="search-input" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                    <button class="btn btn-secondary" id="button-search" type="button" onclick="searchItem()">Go!</button>
                                </div>
                            </div>
                        </div>
                    <!-- Categories widget-->
                        <div class="card mb-2 bg-light" id="categories-card">
                            <div class="card-body">
                                <div class="row">
                                    <ul class = "list-unstyled mb-0">
                                        {% for c in categories %}
                                        <a class ="btn btn-success"  href="http://127.0.0.1:8000/computer/category/{{c.slug}}">{{c}} ({{c.item_set.count}})</a>
                                        {% endfor %}
                                        <a class ="btn btn-success" href="http://127.0.0.1:8000/computer/category/no_category">미분류 ({{no_category}})</a>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    <!-- Maker widget-->
                        <div class="card mb-2" id="maker-card">
                            <div class="card-body">
                                <div class="row">
                                    <ul class = "list-unstyled mb-0">
                                        {% for m in makers %}
                                        <a class ="btn btn-success" href="http://127.0.0.1:8000/computer/maker/{{m.slug}}">{{m}} ({{m.item_set.count}})</a>
                                        {% endfor %}
                                        <a class ="btn btn-success" href="http://127.0.0.1:8000/computer/maker/no_maker">미분류 ({{no_maker}})</a>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                {% if search_info %} <span class="badge bg-secondary">{{search_info}}</span>{% endif %}
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    <!-- 상품 -->
                    {% for p in item_list %}
                    <div class="col mb-5" id="item-{{p.pk}}">
                        <div class="card h-100">
                            <!-- Product images-->

                            {% if p.head_image.url %}
                                <img class="card-img mb-4 img-fluid w-100" src="{{ p.head_image.url }}" alt="..." />
                            {% else %}
                                <img class="card-img mb-4" src="https://picsum.photos/seed/{{p.id}}" alt="..." />
                            {% endif %}

                            <!-- Product details-->
                            <div class="card-body mb-4">
                                <div class="text-center">
                                    {% if p.category %}
                                        <span class="badge bg-secondary float-right">{{ p.category }}</span>
                                    {% else %}
                                        <span class="badge bg-secondary float-right">미분류</span>
                                    {% endif %}
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ p.item_name | truncatewords_html:50 | safe}}</h5>
                                    <!-- Product explanation-->
                                    <h6>{{p.get_explanation_markdown | truncatechars:50 }}</h6>
                                    <!-- Product price-->
                                    {{p.item_price}}
                                    {{p.item_state}}
                                    {{p.item_receipt}}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{{ p.get_absolute_url }}">Details</a></div>
                            </div>
                            <div class="card-footer">
                                <div class = "small text-muted"> {{ p.created_at | date:"20y-m-d" }} by {{p.author | upper}}</div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
        <!-- Pagination-->
        {% if is_paginated %}

        <ul class="pagination justify-content-center my-4">
            {% if page_obj.has_previous %}
            <li class="page-item text-dark">
                <a class="page-link" href="?page={{page_obj.previous_page_number}}" tabindex="-1" aria-disabled="true"> &larr; Newer</a>
            </li>
            {% else %}
            <li class="page-item disabled text-dark">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true"> &larr; Newer</a>
            </li>
            {% endif %}
            {% if page_obj.has_next %}
            <li class="page-item text-dark">
                <a class="page-link" href="?page={{page_obj.next_page_number}}"> Older &rarr;</a>
            </li>
            {% else %}
            <li class="page-item disabled text-dark">
                <a class="page-link" href="#!"> Older &rarr;</a>
            </li>
            {% endif %}
        </ul>
{% endif %}
{% endblock %}